// packages/react/src/hooks.ts
import type { AnalyticsProps } from "@withbeacon/core";
import { track } from "@withbeacon/core";
import { useEffect } from "react";

export function useAnalytics({ before, ...props }: AnalyticsProps) {
  useEffect(
    () =>
      track({
        before: before ? before : (evt) => evt,
        ...props,
      }),
    []
  );
}

// packages/solid-js/src/hooks.ts
import type { AnalyticsProps } from "@withbeacon/core";
import { onMount } from "solid-js";
import { track } from "@withbeacon/core";

export function useAnalytics({ before, ...props }: AnalyticsProps) {
  onMount(() =>
    track({
      before: before ? before : (evt) => evt,
      ...props,
    })
  );
}
